# Label Encoding 
Label Encoding and Ordinal Encoding are the 2 techniques which are used to convert the categorical data into the numerical data.  \

Label Encoding involves the assigning a unique value to each category in the variable and alsohe labels are arranged in alphabetical order or based on the frequency of categories. If we have a categorical variable with 3 possible values such as red, green and blue, we can represent it by label encoding.

In [2]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'color' : ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
from sklearn.preprocessing import LabelEncoder 
lbl_encoder = LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([['red']])

c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [8]:
lbl_encoder.transform([['blue']])

c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [9]:
lbl_encoder.transform([['green']])

c:\Users\91981\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

# Ordinal Encoding 
it is used to encode a  categorical data that has an intrinsic order or ranking. Each technique and each category reers to where each category is assigned a numerical value based on its position i the order.  

1. High School 
2. College 
3. Graduate 
4. Post graduate

In [28]:
df = pd.DataFrame({
    'size' : ['small', 'medium', 'medium', 'small', 'large']
})

In [29]:
df.head()

     size
0   small
1  medium
2  medium
3   small
4   large

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
encoder = OrdinalEncoder(categories = [['small', 'medium', 'large']])

In [32]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [1.],
       [0.],
       [2.]])