# Target_Guided_Ordinal_Encoding 

It is a technique which is used to to encode the categorical variables ased on the relationships with the target variables.  This encoding technique is used to when we have a  categorical vaariable with a large number of the uique categories  and we want to use this variable as a feature.  

In Target Guided Ordinal Encoding, we replaace each category in categorical variable and also with a umerical value based on the mean or the median of the target variable for that category.

In [2]:
import pandas as pd 

df = pd.DataFrame({
    'city' : ['New York', 'London', 'Paris', 'Tokoyo', 'New York', 'Paris'], 
    'price' : [200, 100, 300, 250, 180, 320] 

})

In [3]:
df.head()

       city  price
0  New York    200
1    London    100
2     Paris    300
3    Tokoyo    250
4  New York    180

In [6]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [7]:
mean_price

{'London': 100.0, 'New York': 190.0, 'Paris': 310.0, 'Tokoyo': 250.0}

In [9]:
df['city_encoded'] = df['city'].map(mean_price)

In [10]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    100         100.0
2     Paris    300         310.0
3    Tokoyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [12]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         190.0
1    100         100.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0