# Reading the Data from the Different Sources

In [38]:
import pandas as pd 
from io import StringIO 

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"Title1": "Team Lead", "Title2": "Sr. Developer"}]}' 
df = pd.read_json(StringIO(Data))  
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'Title1': 'Team Lead', 'Title2': 'Sr. Develop..."

Here, as we can see that the Data Frame gets printed like this and it is formed like a table in the tabular form. 
Also, is is to note that the json is like a key value data type written above.

In [39]:
# Converting the data frame back to json takes place as: 
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"Title1":"Team Lead","Title2":"Sr. Developer"}}}'

Here, as we can see that the data frame is getting converted back to json key value pair.

In [40]:
df.to_json(orient ='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"Title1":"Team Lead","Title2":"Sr. Developer"}}}'

Here, as we can see that the value of the index of the table gets printed which is 0. So, basically 0 value gets pprinted as thr data frame is the 0th index.

In [41]:
# we can also try the records method for printing the orient method which will work as: 
df.to_json(orient = 'records')  

# Here as we can see that the tabular data frame is getting printed here in the form of reccords

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"Title1":"Team Lead","Title2":"Sr. Developer"}}]'

In [42]:
# Reading the data from a url can be done as: 
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv") 
df  

# Here, the data from the url gets printed from the url

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [43]:
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [44]:
df.to_csv("diabetes.csv")

Here, the data from the diabetes gets converted to the diabetes csv.

In [45]:
url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv" 
df = pd.read_csv(url) 

df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [46]:
url = "http://www.fdic.gov/bank/individual/failed/banklist.html" 
df = pd.read_html(url) 

df

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

Here, the data gets printed in the form of html table and it gets printed.

In [47]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

Also, the html data gets printed in the form of html.

In [55]:
url = "https://en.wikipedia.org/wiki/List_of_telephone_country_codes"
tables =  pd.read_html(url, header = 0)[0] 

tables[0]  

# here it gives error as because he wikipedia is blocking the request so the proper method for this can be:

HTTPError: HTTP Error 403: Forbidden

In [57]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

# Add headers (this fixes 403 error)
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Get page content
response = requests.get(url, headers=headers)

# Read HTML from response text
tables = pd.read_html(response.text)

df = tables[0]

df.head()

C:\Users\91981\AppData\Local\Temp\ipykernel_8836\2068317419.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [59]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [61]:
# opening an excel file takes place as: 
df_excel = pd.read_excel('data.xlsx')  
df_excel

# Here the data in theexcel file gets printed

  Unnamed: 0 Unnamed: 1
0       Name        Age
1      Krish         32
2       Jack         34
3       John         31

# Pickle File 
Pickle in Python is a process in serializing and describing a Python object structure. It is the process of conveerting a python object to a byte stream.

In [ ]:
df_excel.to_pickle('df_excel') 
# It gets converted to pickle file

In [64]:
# Reading a pickle file 
pd.read_pickle('df_excel')

  Unnamed: 0 Unnamed: 1
0       Name        Age
1      Krish         32
2       Jack         34
3       John         31