# Pandas  
Pandas is a powerful data manipulation library in Python which is widely used for the data analysis and also the data cleaning. It provides the 2 rimary data structures: Series and DataFrame.

A Series is a one dimensional array like object whereas a DataFrame is a two dimensional size mutable and potentially heterogenous tabular data structure with labelled axes as the rows and columns.

In [1]:
import pandas as pd

In [3]:
# Series 
# Pandas Series is a one dimensional array like object that can hold any data type. It is basically similat to column in a table.  

import pandas as pd 
data = [1,2,3,4,5] 
series = pd.Series(data) 
print("Series \n", series)  

print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In the above code, as we can see that the series are getting printed and also, the data in the series is getting printed along with the type of the data.

In [4]:
# Creating a series from the dictionary 
data = {'a':1, 'b':2, 'c':3} 
series_dict = pd.Series(data) 
print(series_dict)

a    1
b    2
c    3
dtype: int64

Here, in the above code, we can see that the letters a, b and c become the index instead of the normal indexing from numbers.

In [ ]:
# Printing the Series by taking the data and index seperately 
data = [10,20,30] 
index = ['a', 'b', 'c'] 

pd.Series(data, index = index)  

# Here, this is the series which are printed here

a    10
b    20
c    30
dtype: int64

In [8]:
# Operation on DataFrame  
# Creating a DataFrame from a dictionary of list  
import pandas as pd 
data = {
    "Name":["Krish", "John", "Jack"], 
    "Age":[25,30,45], 
    "City":["Bangalore", "New York", "Florida"] 
} 

df = pd.DataFrame(data) 

print(df) 
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [ ]:
# Using the numpy in the above code works as: 
import numpy as np 
np.array(df)  

# The whole data is printed in the form of Numpy

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [25]:
# Creates a DataFrame from a List of Dictionaries 

data = [
    {"Name": "Krish", "Age": 32, "City" : "Bangalore"}, 
    {"Name": "John", "Age": 34, "City": "Bangalore"}, 
    {"Name": "Bappy", "Age": 32, "City": "Bangalore"}, 
    {"Name": "Jack", "Age": 32, "City": "Bangalore"}

] 

df = pd.DataFrame(data) 
print(df) 
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   Jack   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [26]:
# Analysing a given dataset from the data as: 
df2 = pd.read_csv("sales_data.csv") 
df2.head(5)  

# Top 5 rows of the whole data is getting printed

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [27]:
# Printignthe last 5 as: 
df2.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
df  
#  Here, the data in the form of a proper tabular representation is getting printed

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   Jack   32  Bangalore

In [29]:
# No, we want to pick up only the name column from the dataset with all its values present in it 
df['Name']

0    Krish
1     John
2    Bappy
3     Jack
Name: Name, dtype: object

Now, suppose if we wnat the 0th row elements to only get printed, then the code for that will be:

In [ ]:
df.loc[0] 
# Row with 0th index is getting printed

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [ ]:
df.loc[0][0]  

# Here, as we can see that it prints the 0th element of the 0th row and Krish gets printed

C:\Users\91981\AppData\Local\Temp\ipykernel_30436\4228444109.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Krish'

In [ ]:
df.loc[0][2]  
# Bangalore will get printed

C:\Users\91981\AppData\Local\Temp\ipykernel_30436\2098363026.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2]

'Bangalore'

In [34]:
df.loc[0][1]

C:\Users\91981\AppData\Local\Temp\ipykernel_30436\183656238.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][1]

np.int64(32)

In [35]:
# Also there are of 2 types loc and iloc which can be explained as: 
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [36]:
df.iloc[0][0]

C:\Users\91981\AppData\Local\Temp\ipykernel_30436\3895442578.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Krish'

In [37]:
df 
# Accessing the whole table

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   Jack   32  Bangalore

In [40]:
# Accessing a specified table takes place as:  
print(df.at[1, 'Age'])

34

In the above code that the Age at the 1th index gets printed here by using the at function.

In [42]:
print(df.at[2, 'Age'])

32

In [ ]:
df.at[2, 'Name']   
# Hre the name at the 2nd index gets printed here

'Bappy'

In [45]:
# Accessing a specified element using iat 
df.iat[2,2]

'Bangalore'

in iat function, we are basically giving both the row index and the column index as it basically tells that the columns have to be from the row of 2nd index and column of the 2nd index.

# Adding of a column 
Now, suppose we have to add a column, then it takes place as:

In [ ]:
# Adding a column as: 
df['Salary'] = [50000, 60000, 70000, 80000]
df  

# The salary column has been added

    Name  Age       City  Salary
0  Krish   32  Bangalore   50000
1   John   34  Bangalore   60000
2  Bappy   32  Bangalore   70000
3   Jack   32  Bangalore   80000

In [ ]:
# Removing a column takes place as: 
df.drop('Salary', axis = 1)  

# Salary column gets removed properly and hence the rest of the data gets printed

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   Jack   32  Bangalore

In the above code we can see that the salary column is a part of column, hence for removing it, we have to write axis = 1 which stands for column, as by default the value is set as axis = 0 which is for rows.

In [ ]:
# Modification of the elements can be easily taken place 
# For example age column  

df['Age'] = df['Age'] + 1 
df  

# here, as we can see that the age gets upgraded

    Name  Age       City  Salary
0  Krish   33  Bangalore   50000
1   John   35  Bangalore   60000
2  Bappy   33  Bangalore   70000
3   Jack   33  Bangalore   80000

In [ ]:
# Dropping the row of the 0th index takes place as 
df.drop(0)  

# 0th index row gets removed

    Name  Age       City  Salary
1   John   35  Bangalore   60000
2  Bappy   33  Bangalore   70000
3   Jack   33  Bangalore   80000

In [ ]:
df2.head(5)  
## Here, the data is getting printed properly

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

# Some important attributes

In [53]:
# Dsiplaying the data types of each column as: 
print("Data Types:\n", df.dtypes) 

# Describing the DataFrame 
print("Statistical Summary:\n", df.describe())

Data Types:
 Name      object
Age        int64
City      object
Salary     int64
dtype: object
Statistical Summary:
         Age        Salary
count   4.0      4.000000
mean   33.5  65000.000000
std     1.0  12909.944487
min    33.0  50000.000000
25%    33.0  57500.000000
50%    33.0  65000.000000
75%    33.5  72500.000000
max    35.0  80000.000000

In [55]:
# Sattistical Summary can be printed as: 
df2.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

# Groupby Colum 
Groupby a column and perform an aggregation

In [58]:
grouped = df2.groupby('Product Category')['Total Revenue'].mean() 
print("Mean Value by Category:\n", grouped)

Mean Value by Category:
 Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64