# Data Analysis and Analysis with Pandas

Data Manipulation and analysis are the key tasks in any data science or data analysis projects. Pandas provide a wide range of the functions for data manipulation and analysis, making it easire to clean, transform and extract insights from the data.  

Here, we are talking about the Data Manipulation and analysis techniques from Pandas.

In [2]:
import pandas as pd 
df = pd.read_csv("sales_data.csv")  
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [3]:
# Fetching the first 5 rows 
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [4]:
# Fetching the last 5 rows 
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [5]:
# Getting all the statistical data to get printed 
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In the above code, as we cans ee that we get all the statistical data like the count, mean,  standard deviation, min etc.

In [6]:
# Printing the data types of the columns which can be done as:  
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In the above code, we get the data type of each and every column.

# Handling the Missing Values

In [ ]:
df.isnull() 

# Here, false means that there are no missing values in the data and tru means the presence of the missing values

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
235,False,False,False,False,False,False,False,False,False
236,False,False,False,False,False,False,False,False,False
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().astype(int)  
# Here 0 menas a non missing value and 0 means a non missing value

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
235,0,0,0,0,0,0,0,0,0
236,0,0,0,0,0,0,0,0,0
237,0,0,0,0,0,0,0,0,0
238,0,0,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0

In [ ]:
# Now, suppose, if we want the data in the form of the list where each is printed with true or false depending on the presence or absence
# of the missing values 

df.isnull().any(axis = 1)  
# Here false means the non missing values and true means the missing values  
# Here the axis = 1 stands for the columns and it shows the distribution column wise

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [ ]:
# Getting the values that whether any missing value present in any column or not 
df.isnull().any()  
# Here, as we can see that there are no missing values present in the column

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [ ]:
# Now, if we want the empty values in the form of numerical data, then we can perform as:  
df.isnull().sum()  

# Hee, there are no empty values present in the data

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

Filling the missing values with the fillna function can be done as:

In [14]:
df.fillna(0)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

This is the function to fill al the missing values with the value 0, but since in this data. there are no missing values, hence the data is seen normal.

In [16]:
# Filling the missing values with the mean of the column 
df["Total Revenue"] = df['Total Revenue'].fillna(df['Total Revenue'].mean()) 
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

The above method is basically used for printing the columns with the mean of the missing values and hence, now the missing values are being printed here.

In [17]:
# Prinitng the data types of the columns as: 
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In the above code, we can see that the Date, Product Category, Product Name, Region and Payment Method are all the data types present in the columns.

# Renaming the columns 
Here, in the code , we will be seeing to rename the column names in the whole data to perform the renaming as:

In [ ]:
df = df.rename(columns= {"Date":"Sale Date"})  
df  

# An important note is that, we need to give the renaming in the form of key value pairs

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In the above code, as we can see that the data column name gets changed to sale date column name.

In [19]:
# Changing the data types take place as by the astype function  
df["Units Sold"] = df["Units Sold"].astype(float) 
df

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2.0,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1.0,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3.0,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4.0,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1.0,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1.0,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3.0,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3.0,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1.0,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2.0,29.99,59.98,Asia,Credit Card

Here, in the above code we can see that the values in the column get converted from the integers to float.

In [20]:
# Filling the missing values along with the cahnging the data types takes place as: 
df["Units Sold"] = df["Units Sold"].fillna(df["Units Sold"].mean()).astype(int) 
df

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

Here, in the above code as we can see that the float values again get converted to the integer and if there would have been missing values, then they would have converted to mean.

In [21]:
# Now, suppose we have to apply any function on a siingle column among the whole data .
# Then it can be done as: 

df["New Units Sold"] = df["Units Sold"].apply(lambda x:x*2) 
df.head()

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,New Units Sold
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,6
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,8
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,2

Here, as we can see that in the new column each value gets printed to the twice of the previous value by applying the lambda function.

# Data Aggregation and Grouping 
Now, we will be performing the data aggragation and its grouping.

In [ ]:
df.head(5)  
# The top 5 values of the whole data are getting printed here properly and ow the gouping will take place

,Transaction ID,Sale Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,New Units Sold
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,6
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,8
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,2

Here we will be grouping by among the categorial and the numerical datas and will be used to calculate the mean.

In [25]:
grouped_mean = df.groupby('Product Name')['Total Revenue'].mean() 
print(grouped_mean)

Product Name
1984 by George Orwell                                   79.96
Adidas 3-Stripes Shorts                                149.95
Adidas Essential Track Pants                           134.97
Adidas FIFA World Cup Football                          89.97
Adidas Originals Superstar Sneakers                    319.96
                                                       ...
Yeti Tundra Haul Portable Wheeled Cooler               399.99
Youth to the People Superfood Antioxidant Cleanser      36.00
Zara Summer Dress                                      179.97
iPhone 14 Pro                                         1999.98
iRobot Braava Jet M6                                   449.99
Name: Total Revenue, Length: 232, dtype: float64

In [ ]:
df['Product Name'].count() 
# Here there are total of 240 valuesin the whole column and the mean value of each gets printed

np.int64(240)

Now, we will  be taking the 2 values into account to do the grouoing and carry the analysis of grouping the data and this time using the sum() function.

In [29]:
grouped_sum = df.groupby(['Product Name', 'Region'])['Units Sold'].sum() 
print(grouped_sum)

Product Name                                        Region
1984 by George Orwell                               North America    4
Adidas 3-Stripes Shorts                             Asia             5
Adidas Essential Track Pants                        Asia             3
Adidas FIFA World Cup Football                      Asia             3
Adidas Originals Superstar Sneakers                 Asia             4
                                                                    ..
Yeti Tundra Haul Portable Wheeled Cooler            Asia             1
Youth to the People Superfood Antioxidant Cleanser  Europe           1
Zara Summer Dress                                   Asia             3
iPhone 14 Pro                                       North America    2
iRobot Braava Jet M6                                Europe           1
Name: Units Sold, Length: 233, dtype: int64

So, basically based on 2 categories, we are grouping it and doing the sum of the values based on the categories.

In [31]:
# The above same code, we can apply by using the mean also in the data as: 
grouped_sum = df.groupby(['Product Name', 'Region'])['Units Sold'].mean() 
print(grouped_sum)

Product Name                                        Region
1984 by George Orwell                               North America    4.0
Adidas 3-Stripes Shorts                             Asia             5.0
Adidas Essential Track Pants                        Asia             3.0
Adidas FIFA World Cup Football                      Asia             3.0
Adidas Originals Superstar Sneakers                 Asia             4.0
                                                                    ...
Yeti Tundra Haul Portable Wheeled Cooler            Asia             1.0
Youth to the People Superfood Antioxidant Cleanser  Europe           1.0
Zara Summer Dress                                   Asia             3.0
iPhone 14 Pro                                       North America    2.0
iRobot Braava Jet M6                                Europe           1.0
Name: Units Sold, Length: 233, dtype: float64

# Aggregating Multiple Functions 
Now, we will be aggregating the multiple functions and it will take place as:

In [32]:
grouped_agg = df.groupby('Region')['Units Sold'].agg(['mean', 'sum', 'count']) 
grouped_agg

                 mean  sum  count
Region
Asia           2.9125  233     80
Europe         1.3125  105     80
North America  2.2500  180     80

Here, as we can see that the region wise analysis of the whole data is present here.

# Merging and Joining the Data Frames 
Creating the sample data frames

In [33]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1,2,3]}) 
df2 = pd.DataFrame({'Key': ['A', 'B','D'], 'Value2': [4,5,6]})

In [ ]:
df1  
# Here df1 gets printed in the tabular form properly

  Key  Value1
0   A       1
1   B       2
2   C       3

In [ ]:
df2  
# df2 also gets printed in the tabular form properly

  Key  Value2
0   A       4
1   B       5
2   D       6

# Merging the 2 data frames 
Now, we will be merging the 2 dataframes by applying the codes.

In [ ]:
pd.merge(df1, df2, on = "Key", how = "inner")  

# Here, as we can see that both these data frames ae getting merged here on the column name Key and the join taking place is inner

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In the above code, the inner parameter basically mean that the joining takes place on the same solumns in both, Now, we try the other joining parameters which take place as:

In [ ]:
pd.merge(df1, df2, on = "Key", how = "outer")  
# This is because C has no value 2 and D has no value 1

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [39]:
# Trying the left parameter for joining can be done as: 
pd.merge(df1, df2, on = "Key", how = "left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In the above coode, we can see that since the df1 is present on the left, so its given more priority and the values of C get printed here.

In [ ]:
pd.merge(df1, df2, on = "Key", how = "right")  
# Here, since d2 is on right, so its given priority

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [ ]:
pd.merge(df1, df2)  
# Here by default it gets printed like inner

  Key  Value1  Value2
0   A       1       4
1   B       2       5